[site]
# The title of the site
title = "|> Sam Macpherson Media"
# The name of the author
author = "/* Sam Macpherson */"

date = "2023"

description = "// Hey, I'm Sam. I'm a photographer and videographer based in Samford Valley Qld" 

[[site.nav]]
icon = "assets/icons/instagram.svg"
link = "https://instagram.com/sam.thegibbon"

[[site.nav]]
icon = "assets/icons/facebook.svg"
link = "https://facebook.com/sam.macpherson"

[[site.nav]]
icon = "assets/icons/email.svg"
link = "mailto:sam.macpherson@outlook.com"

# Layout for grids
[layout]
minColumn = 2
maxColumn = 6
minWidth = 100

# Setttings for photo size
[image]
# Width for thumbnail images
thumbnailWidth = 640
# Width for enlarged images
originalWidth = 2048

[[section]]
title = "Small business |> Case Study"
text = "Matt & Lamisha from Creative Roots Breath Thearapy are a small business based in Brisbane, Australia. They offer a range of services including breathwork, meditation and sound healing. They are passionate about helping people to heal and grow through these practices. I was lucky enough to work with them to create a short instagram reel and photo series to help promote their business."
link = "https://www.creativerootsbreaththerapy.com/"
slug = "workshops"
folder = "photos/workshops"

[[section]]
title = "Small Business |> Case Study"
link = "https://www.samfordlive.au"
text = """
"Samford Live is a locally inspired, community based, not for profit run by artists. They aim to enrich the culture of our local community through music.." 
 I love live music and the samford live crew and I now collaborate on each show to create a photo series to help promote the next event. 
"""
slug = "events"
folder = "photos/events"

[[section]]
title = "|> Men's Work Movements"
text = """
I've worked with several men's work practioners & leaders in the space
to bring more awareness around the men's work movement.
I love these spaces and have gained a lot from both particpating and sharing 
what I capture in these spaces with the men participating and the community at large.
"""
link = ""
slug = "retreats"
folder = "photos/retreats"


# Other setings
[others]
# Folders that should be copied together when exporting sites
folders = [ "assets", "media" ]
# Show `Generated by foto` footer or not
show_foto_footer = true
